### ISSUE TITLE
Getting GPS Data through UDP

### ISSUE THREAD

**Issue by Asratum** [jrenken/qgis-PosiView#9]
I can successfully listen to UDP data on my PC:
![image](https://user-images.githubusercontent.com/60708813/189533208-88d0e65b-4e5d-4714-819d-d2304f93bc08.png)

However, with PosiView the same settings result in a greyed out button and no data:
![image](https://user-images.githubusercontent.com/60708813/189533277-7a4f050a-da36-4bae-92fd-78bb0b63489e.png)

Do you have any idea how I can start troubleshooting? Is there any place where PosiView outputs some kind of error messages?

**Comment by qbazd** [comment]
Hi,

Try hosts: 
0.0.0.0 (default listen on all current host IP's)
or
10.47.137.255 (I think it is your network broadcast IP if your net mask is 255.255.255.0 or /24) 

Longer answer:
Config of "UDP Host" in PosiView is an IP address for listening for packets, it is like TCP server mode, it is not like TCP client mode where IP is host to connect to.
And is has different meaning than "UDP Host" in your "Hercules setup utility" Because of setting up two way communication. Where is UDP Host is to send packets to. And listening is configured only by UDP port, and UDP IP aka Host is probably set to default (0.0.0.0).

Under linux I normally use NetCat, iptraf to debug UDP.

**Comment by jrenken** [comment]
Hi,
as qbazd stated, 0.0.0.0 or the IP of the associated interface is the correct value when receiving UDP traffic. The broadcast address does not work.
You also have to close all other tools that access the port, because a port can only be bound by one socket.

Thanks Jakub.

**Comment by Asratum** [comment]
Thanks you for your advice!
I managed to get it to work by setting to my own IP, which I got from IP config:
![image](https://user-images.githubusercontent.com/60708813/191036783-afbdf148-6e97-4e6f-b5ae-9119ccb5468e.png)

After that it was still greyed out, I didn't realize you have to click Start/Stop Tracking to turn the data stream on:
![image](https://user-images.githubusercontent.com/60708813/191037415-b419456d-0722-407d-b78f-77abcd2c1acf.png)

Perhaps as a feedback: I find it a bit confusing, that start and stop tracking starts and stops listening to the signal, I was expecting my NavPC button to turn on green whenever data was coming in, not only when I start the tracking.
